[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true

[ui]
pageTitle = "Suivi VACPA"
favicon = "https://github.com/marwa-werghemi/vacpa-suivi-rendement/blob/master/ChatGPT%20Image%2020%20mai%202025%2C%2022_08_31.png"  # ou ton propre lien .ico ou .png
Ajout du fichier de configuration Streamlit
